const $ = id => document.getElementById(id);
const state = { data:{}, progress: JSON.parse(localStorage.getItem('skyProgress') || '{}'), chartDeck:[], chartCurrent:null, neighbourCurrent:null, starCurrent:null, dsoCurrent:null, abbrCurrent:null, timer:null, timerRemaining:600, timerFound:new Set(), table:'constellations' };
function save(){ localStorage.setItem('skyProgress', JSON.stringify(state.progress)); renderDashboard(); }
function bump(key, ok){ if(!state.progress[key]) state.progress[key]={seen:0,correct:0}; state.progress[key].seen++; if(ok) state.progress[key].correct++; save(); }
function norm(s){ return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(); }
function rand(a){ return a[Math.floor(Math.random()*a.length)]; }
function shuffle(a){ for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; }
function sample(arr,n,exclude=()=>false){ const pool=shuffle(arr.filter(x=>!exclude(x)).slice()); return pool.slice(0,n); }
function setMsg(el,text,good=false){ el.textContent=text; el.className='message '+(text?(good?'good':'bad'):''); }
function accepts(guess, answers){ const g=norm(guess); return answers.some(a=>norm(a)===g); }
function displayAcc(p){ return p ? Math.round(100*p.correct/Math.max(1,p.seen))+'%' : '0%'; }
async function load(){ const names=['constellations','charts','messier','caldwell','stars']; for(const n of names){ state.data[n]=await (await fetch(`data/${n}.json`)).json(); } state.data.dso=[...state.data.messier,...state.data.caldwell]; initTabs(); initChart(); initNeighbour(); initStars(); initDSO(); initTimer(); initAbbr(); initAtlas(); initTables(); renderDashboard(); }
function renderDashboard(){ const keys=[['chart','Chart Quiz'],['neighbour','Neighbour Web'],['stars','Star Names'],['dso','DSOs'],['abbr','Abbrev Sprint'],['timer','88 Timer']]; $('dashboard').innerHTML=keys.map(([k,label])=>{const p=state.progress[k]||{seen:0,correct:0}; return `<div class="pill"><strong>${label}</strong><br>${p.correct}/${p.seen} correct (${displayAcc(p)})</div>`}).join(''); }
function initTabs(){ document.querySelectorAll('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{ document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active')); $(btn.dataset.tab).classList.add('active'); })); $('resetProgress').onclick=()=>{ if(confirm('Reset saved progress?')){ state.progress={}; save(); } }; }
function refillChart(){ state.chartDeck=state.data.charts.map((_,i)=>i); if($('chartShuffle').checked) shuffle(state.chartDeck); }
function initChart(){ refillChart(); $('chartShuffle').onchange=refillChart; $('chartSubmit').onclick=submitChart; $('chartReveal').onclick=()=>revealChart(false); $('chartNext').onclick=nextChart; $('chartGuess').onkeydown=e=>{if(e.key==='Enter')submitChart();}; nextChart(); }
function nextChart(){ if(!state.chartDeck.length) refillChart(); state.chartCurrent=state.chartDeck.pop(); const c=state.data.charts[state.chartCurrent]; $('chartImg').src=c.image; $('chartAnswer').classList.add('hidden'); $('chartGuess').value=''; setMsg($('chartMsg'),''); renderChartStats(); $('chartGuess').focus(); }
function renderChartStats(){ const p=state.progress.chart||{seen:0,correct:0}; $('chartStats').innerHTML=`<div><strong>${p.seen}</strong><br>seen</div><div><strong>${p.correct}</strong><br>correct</div><div><strong>${displayAcc(p)}</strong><br>accuracy</div>`; }
function revealChart(auto){ const c=state.data.charts[state.chartCurrent]; $('chartAnswer').innerHTML=`<h3>${c.displayName}</h3><p>Abbreviation: ${c.abbr}. Visible neighbouring labels on this chart: ${c.neighbours.join(', ') || 'none detected'}.</p>${$('chartAnswerImage').checked?`<img src="${c.answerImage}" alt="Labelled answer chart">`:''}`; $('chartAnswer').classList.remove('hidden'); if(!auto) setMsg($('chartMsg'),`Answer: ${c.displayName}`); }
function submitChart(){ const c=state.data.charts[state.chartCurrent]; const ok=accepts($('chartGuess').value,c.accepted); bump('chart',ok); setMsg($('chartMsg'), ok?`Correct - ${c.displayName}`:'Not quite. Try again or reveal.', ok); if(ok) revealChart(true); renderChartStats(); }
function initNeighbour(){ $('neighbourNext').onclick=nextNeighbour; nextNeighbour(); }
function nextNeighbour(){ const candidates=state.data.charts.filter(c=>c.neighbours.length); const c=rand(candidates); const ans=rand(c.neighbours); state.neighbourCurrent={chart:c,answer:ans}; $('neighbourImg').src=c.image; $('neighbourPrompt').innerHTML=`On the <strong>${c.displayName}</strong> chart, which of these constellations also appears nearby?`; const wrong=sample(state.data.constellations.map(x=>x.name),3,x=>x===ans || c.neighbours.includes(x)); const choices=shuffle([ans,...wrong]); $('neighbourChoices').innerHTML=choices.map(ch=>`<button>${ch}</button>`).join(''); [...$('neighbourChoices').children].forEach(b=>b.onclick=()=>chooseNeighbour(b)); setMsg($('neighbourMsg'),''); }
function chooseNeighbour(btn){ const ok=btn.textContent===state.neighbourCurrent.answer; bump('neighbour',ok); [...$('neighbourChoices').children].forEach(b=>{ if(b.textContent===state.neighbourCurrent.answer)b.classList.add('correct'); else if(b===btn)b.classList.add('wrong'); b.disabled=true; }); setMsg($('neighbourMsg'), ok?'Correct.':'Not quite. This is a relative-position clue: study the chart, then move to the neighbouring chart.', ok); }
function initStars(){ $('starMode').onchange=nextStar; $('starNext').onclick=nextStar; $('starReveal').onclick=()=>revealStar(false); $('starSubmit').onclick=submitStar; $('starGuess').onkeydown=e=>{if(e.key==='Enter')submitStar();}; nextStar(); }
function starAnswer(item,mode){ if(mode==='constellation') return {answer:item.constellation, prompt:`Which constellation contains <strong>${item.name}</strong>?`, pool:state.data.constellations.map(c=>c.name)}; if(mode==='designation') return {answer:item.designation, prompt:`What is the designation of <strong>${item.name}</strong>?`, pool:state.data.stars.map(s=>s.designation)}; return {answer:item.name, prompt:`Which named star has designation <strong>${item.designation}</strong>?`, pool:state.data.stars.map(s=>s.name)}; }
function nextStar(){ const item=rand(state.data.stars); const mode=$('starMode').value; const q=starAnswer(item,mode); state.starCurrent={item,q}; $('starPrompt').innerHTML=q.prompt; const choices=shuffle([q.answer,...sample(q.pool,3,x=>norm(x)===norm(q.answer))]); $('starChoices').innerHTML=choices.map(ch=>`<button>${ch}</button>`).join(''); [...$('starChoices').children].forEach(b=>b.onclick=()=>chooseStar(b)); $('starGuess').value=''; $('starInfo').innerHTML=`<p><strong>${item.name}</strong></p><p>${item.note}</p><p class="small">Designation: ${item.designation}. Constellation: ${item.constellation}.</p>`; setMsg($('starMsg'),''); }
function chooseStar(btn){ const ok=norm(btn.textContent)===norm(state.starCurrent.q.answer); bump('stars',ok); [...$('starChoices').children].forEach(b=>{ if(norm(b.textContent)===norm(state.starCurrent.q.answer))b.classList.add('correct'); else if(b===btn)b.classList.add('wrong'); b.disabled=true; }); setMsg($('starMsg'), ok?'Correct.':`Answer: ${state.starCurrent.q.answer}`, ok); }
function submitStar(){ const ok=accepts($('starGuess').value,[state.starCurrent.q.answer]); bump('stars',ok); setMsg($('starMsg'), ok?'Correct.':`Answer: ${state.starCurrent.q.answer}`, ok); }
function revealStar(){ setMsg($('starMsg'),`Answer: ${state.starCurrent.q.answer}`); }
function initDSO(){ $('dsoMode').onchange=nextDSO; $('dsoCatalogue').onchange=nextDSO; $('dsoNext').onclick=nextDSO; $('dsoReveal').onclick=()=>revealDSO(false); $('dsoSubmit').onclick=submitDSO; $('dsoGuess').onkeydown=e=>{if(e.key==='Enter')submitDSO();}; nextDSO(); }
function dsoPool(){ const cat=$('dsoCatalogue').value; return state.data.dso.filter(x=>cat==='both'||x.catalog===cat); }
function labelDSO(o){ return `${o.code}${o.commonName?` - ${o.commonName}`:''}`; }
function dsoQuestion(item,mode){ if(mode==='nameToCode'){ const clue=item.commonName||rand(item.aliases)||item.type; return {prompt:`<strong>${clue}</strong> in ${item.constellation}: which catalogue number?`, answer:item.code, pool:dsoPool().map(x=>x.code)}; } if(mode==='constellation') return {prompt:`Which constellation contains <strong>${labelDSO(item)}</strong>?`, answer:item.constellation, pool:state.data.constellations.map(c=>c.name)}; if(mode==='type') return {prompt:`What type of object is <strong>${labelDSO(item)}</strong>?`, answer:item.type, pool:[...new Set(state.data.dso.map(x=>x.type))]}; return {prompt:`What common name is associated with <strong>${item.code}</strong>?`, answer:item.commonName||item.aliases[0]||item.type, pool:dsoPool().map(x=>x.commonName||x.aliases[0]||x.type)}; }
function nextDSO(){ const item=rand(dsoPool()); const q=dsoQuestion(item,$('dsoMode').value); state.dsoCurrent={item,q}; $('dsoPrompt').innerHTML=q.prompt; const choices=shuffle([q.answer,...sample(q.pool,3,x=>norm(x)===norm(q.answer))]); $('dsoChoices').innerHTML=choices.map(ch=>`<button>${ch}</button>`).join(''); [...$('dsoChoices').children].forEach(b=>b.onclick=()=>chooseDSO(b)); $('dsoGuess').value=''; $('dsoInfo').innerHTML=`<p><strong>${labelDSO(item)}</strong></p><p>${item.type} in ${item.constellation}</p><p class="small">Aliases/designations: ${item.aliases.join(', ') || 'none listed'}</p>`; setMsg($('dsoMsg'),''); }
function chooseDSO(btn){ const ok=norm(btn.textContent)===norm(state.dsoCurrent.q.answer); bump('dso',ok); [...$('dsoChoices').children].forEach(b=>{ if(norm(b.textContent)===norm(state.dsoCurrent.q.answer))b.classList.add('correct'); else if(b===btn)b.classList.add('wrong'); b.disabled=true; }); setMsg($('dsoMsg'), ok?'Correct.':`Answer: ${state.dsoCurrent.q.answer}`, ok); }
function submitDSO(){ const answers=[state.dsoCurrent.q.answer,...state.dsoCurrent.item.accepted]; const ok=accepts($('dsoGuess').value,answers); bump('dso',ok); setMsg($('dsoMsg'), ok?'Correct.':`Answer: ${state.dsoCurrent.q.answer}`, ok); }
function revealDSO(){ setMsg($('dsoMsg'),`Answer: ${state.dsoCurrent.q.answer}`); }
function initTimer(){ renderTimerLists(); $('timerStart').onclick=startTimer; $('timerStop').onclick=stopTimer; $('timerInput').onkeydown=e=>{ if(e.key==='Enter') timerSubmit(); }; }
function startTimer(){ stopTimer(); state.timerFound=new Set(); state.timerRemaining=parseInt($('timerMinutes').value,10)*60; $('timerInput').disabled=false; $('timerInput').focus(); state.timer=setInterval(()=>{ state.timerRemaining--; renderTimerClock(); if(state.timerRemaining<=0) stopTimer(true); },1000); renderTimerClock(); renderTimerLists(); setMsg($('timerMsg'),'Go.'); }
function stopTimer(done=false){ if(state.timer){clearInterval(state.timer); state.timer=null;} if(done){ bump('timer', state.timerFound.size===88); setMsg($('timerMsg'),`Time. Score: ${state.timerFound.size}/88`, state.timerFound.size===88); } }
function renderTimerClock(){ const m=String(Math.floor(state.timerRemaining/60)).padStart(2,'0'); const s=String(state.timerRemaining%60).padStart(2,'0'); $('timerClock').textContent=`${m}:${s}`; }
function timerSubmit(){ const g=$('timerInput').value; $('timerInput').value=''; const hit=state.data.constellations.find(c=>[c.name,c.abbr,...(c.aliases||[])].some(a=>norm(a)===norm(g))); if(!hit){ setMsg($('timerMsg'),'No match. Check spelling or try another.'); return; } if(state.timerFound.has(hit.name)){ setMsg($('timerMsg'),`${hit.name} already found.`); return; } state.timerFound.add(hit.name); setMsg($('timerMsg'),`Found ${hit.name}. ${state.timerFound.size}/88`,true); renderTimerLists(); if(state.timerFound.size===88){ stopTimer(false); bump('timer',true); setMsg($('timerMsg'),'All 88 found.',true); } }
function renderTimerLists(){ const found=[...state.timerFound].sort(); const missing=state.data.constellations.map(c=>c.name).filter(n=>!state.timerFound.has(n)); $('timerFound').innerHTML=found.map(n=>`<span class="pill">${n}</span>`).join(''); $('timerMissing').innerHTML=missing.map(n=>`<span class="pill">${n}</span>`).join(''); }
function initAbbr(){ $('abbrMode').onchange=nextAbbr; $('abbrNext').onclick=nextAbbr; $('abbrSubmit').onclick=submitAbbr; $('abbrReveal').onclick=()=>setMsg($('abbrMsg'),`Answer: ${state.abbrCurrent.answer}`); $('abbrGuess').onkeydown=e=>{if(e.key==='Enter')submitAbbr();}; nextAbbr(); }
function nextAbbr(){ const c=rand(state.data.constellations); if($('abbrMode').value==='nameToAbbr') state.abbrCurrent={prompt:`What is the IAU abbreviation for <strong>${c.name}</strong>?`,answer:c.abbr,accepted:[c.abbr,c.abbr.toUpperCase()]}; else state.abbrCurrent={prompt:`Which constellation is <strong>${c.abbr}</strong>?`,answer:c.name,accepted:[c.name,...(c.aliases||[])]}; $('abbrPrompt').innerHTML=state.abbrCurrent.prompt; $('abbrGuess').value=''; setMsg($('abbrMsg'),''); }
function submitAbbr(){ const ok=accepts($('abbrGuess').value,state.abbrCurrent.accepted); bump('abbr',ok); setMsg($('abbrMsg'),ok?'Correct.':`Answer: ${state.abbrCurrent.answer}`,ok); }
function initAtlas(){ $('atlasGrid').innerHTML=state.data.charts.map(c=>`<div class="atlas-card" data-id="${c.id}"><img src="${c.image}" alt="${c.displayName}"><h3>${c.displayName}</h3><p class="small">Click to reveal labels. Neighbours: ${c.neighbours.slice(0,6).join(', ')}</p></div>`).join(''); document.querySelectorAll('.atlas-card').forEach(card=>card.onclick=()=>{ const c=state.data.charts.find(x=>x.id===card.dataset.id); const img=card.querySelector('img'); img.src=img.src.endsWith(c.answerImage)?c.image:c.answerImage; }); }
function initTables(){ document.querySelectorAll('.table-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.table-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.table=b.dataset.table;renderTable();}); $('tableSearch').oninput=renderTable; renderTable(); }
function renderTable(){ const q=norm($('tableSearch').value); let rows=[]; if(state.table==='constellations'){ rows=state.data.constellations.map(c=>[c.name,c.abbr,(c.aliases||[]).join(', ')]); $('tableWrap').innerHTML=makeTable(['Constellation','Abbr','Aliases'], rows, q); } else if(state.table==='stars'){ rows=state.data.stars.map(s=>[s.name,s.designation,s.constellation,s.note]); $('tableWrap').innerHTML=makeTable(['Star','Designation','Constellation','Hook'], rows, q); } else { rows=state.data.dso.map(o=>[o.code,o.commonName,o.type,o.constellation,o.aliases.join(', ')]); $('tableWrap').innerHTML=makeTable(['Code','Common name','Type','Constellation','Aliases'], rows, q); } }
function makeTable(headers, rows, q){ const filtered=rows.filter(r=>!q||norm(r.join(' ')).includes(q)); return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${filtered.map(r=>`<tr>${r.map(x=>`<td>${x||''}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
load();
